---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-app
  labels:
    app: e2e-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2e-app
  template:
    metadata:
      labels:
        app: e2e-app
    spec:
      containers:
        - name: app
          image: ghcr.io/goldschmidt-digital/e2e-tenant-fixture/e2e-app:sha-c201743  # yamllint disable-line rule:line-length
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command: ["wget", "-q", "-O", "/dev/null", "http://127.0.0.1:80/"]
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["wget", "-q", "-O", "/dev/null", "http://127.0.0.1:80/"]
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
